### ISSUE TITLE
Minor suggestions for README.md and CONTRIBUTING.md

### ISSUE THREAD

**Issue by goldst** [entenjaeger2/alice_rs#2]
Hi @firefighterduck, well done! There are a few small and really subjective (feel free to ignore all of them) ideas on how You could present Your project a little bit better.

## README.md
- The file doesn't contain a link to CONTRIBUTING.md. Even though that file is, in theory, accessible anyways, that would seem even more inviting.
- Also, You could add a tiny section at the bottom that links to the LICENSE file.
- Depending on who the target audience is, it might be useful to explain directly in the README.md file what parts of the grammar mean what in practice. A short intro would be sufficient, after which You could link back to Your paper once more. As someone with little experience in that area, the README alone didn't give me an idea of what I just ran.
- The link to *A Decidable Fragment of Separation Logic* doesn't work (there is a `]` at the end that doesn't belong there)

## CONTRIBUTING.md
I really liked how the CONTRIBUTING.md file guided me through the process of getting to know the project step by step!
- You could link to the rustfmt and clippy projects directly
- Even if You don't want a fixed contribution schema, it might still be useful to advise people to create an issue first if they want to work on the code. That way, the chance that somebody is disappointed is smaller at the end.

## Other suggestions
- You could add issue templates to make communication a bit more clear and standardized
- You could also disable the Releases and Packages sections under the About section to give the page a cleaner look

Everything else was really good!

**Comment by firefighterduck** [comment]
Thank you for your constructive feedback. I tried to incorporate it as much as possible.
The only point I'm rather hesitant to apply is the usage of templates as I still haven't found out whether these work for both Github and Gitlab. And I don't really want to have this restriction on a  specific platform within the repository itself.
I will try to find a way around this issue but will leave it for now.
